Feature relay mailgun
cloudposse/postfix pull request #1
Opened 2017-03-09 18:30 UTC by goruha

2017-03-09 18:51 UTC, osterman commented on rootfs/start
> +--relay-auth-enabled       Set relay authenticate enabled
`s/authenticate/authentication/`

2017-03-09 18:51 UTC, osterman commented on rootfs/start
> +--relay-auth-tls           Set relay authenticate using tls
`s/tls/TLS/`

2017-03-09 18:52 UTC, osterman commented on rootfs/start
>  do
can we add an `echo "Waiting for postfix master to exit..."; sleep 1;`

2017-03-09 19:24 UTC, osterman requested changes
See inline comments

2017-03-10 07:00 UTC, goruha commented on rootfs/start
> +--relay-auth-enabled       Set relay authenticate enabled
Done

2017-03-10 07:00 UTC, goruha commented on rootfs/start
> +--relay-auth-tls           Set relay authenticate using tls
Done

2017-03-10 07:01 UTC, goruha commented on rootfs/start
>  do
This will produce a lot of trunk in logs.

2017-03-10 17:04 UTC, osterman commented on rootfs/start
>  do
that's why there is a sleep... =)  no strong opinion on it, but I always error on more output the better.

2017-03-10 17:13 UTC, osterman approved these changes
No strong opinion regarding sleep output, so approving it

2017-03-10 22:41 UTC, merged

2017-03-16 14:41 UTC, goruha commented on rootfs/start
>  do
Nope. This is start script. 
This loop runs until container removed. 
Or postfix failed.

2017-03-16 15:46 UTC, osterman commented on rootfs/start
>  do
Doh! You're totally correct. Thanks for explaining.